name: caparrot
description: Caparrot's pubspec
publish_to: "none"
version: 1.0.0-alpha

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  audioplayers: ^3.0.1
  card_slider: ^1.0.5
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  google_sign_in: ^5.4.4
  introduction_screen: ^3.1.4
  introduction_story: ^0.1.0
  model_viewer_plus: ^1.5.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/music/
    - assets/mapstyle/
    - assets/markers/
    - assets/modelos3d/
    - assets/tutorial/
    - assets/caparrots/
    - data/
  # To add custom fonts to your application:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  color: "#008f4c"
  image: assets/splashscreen/splash.png
