// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDnLvvZtx3GDwT-pE_lF1ObwCi7-UFgI',
    appId: '1:350095021061:web:8a6c5b0c755b5c094eb86c',
    messagingSenderId: '350095021061',
    projectId: 'caparrot-87657',
    authDomain: 'caparrot-87657.firebaseapp.com',
    storageBucket: 'caparrot-87657.appspot.com',
    measurementId: 'G-22JQG7P5K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9UW5lSEZOqW85Z5dEF0nUnOEHyXRp6E',
    appId: '1:350095021061:android:1b7ba721b82839924eb86c',
    messagingSenderId: '350095021061',
    projectId: 'caparrot-87657',
    storageBucket: 'caparrot-87657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHcgAOB2YvaqifklChDpGFIyYW_ppQ0sw',
    appId: '1:350095021061:ios:d7771fff8f261ee24eb86c',
    messagingSenderId: '350095021061',
    projectId: 'caparrot-87657',
    storageBucket: 'caparrot-87657.appspot.com',
    iosClientId: '350095021061-lg1990shd4lscc3rfecibkgborvgjmuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.caparrot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHcgAOB2YvaqifklChDpGFIyYW_ppQ0sw',
    appId: '1:350095021061:ios:d7771fff8f261ee24eb86c',
    messagingSenderId: '350095021061',
    projectId: 'caparrot-87657',
    storageBucket: 'caparrot-87657.appspot.com',
    iosClientId: '350095021061-lg1990shd4lscc3rfecibkgborvgjmuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.caparrot',
  );
}
